### ISSUE TITLE
Update intro doc

### ISSUE THREAD

**Issue by dkirkby** [andreicuceu/lyafit#111]
Since `git:` URIs no longer work, the intro should specify:
```
git clone https://github.com/andreicuceu/vega.git
```
Also, the resulting package dir is `vega`, not `Vega` so the `cd` command should probably be updated.

Finally, if you would like to include instructions for a custom conda env, this worked for me:
```
conda create --name vega pip ipython jupyter jupyterlab ipykernel numpy scipy astropy numba h5py setuptools "iminuit>=2.0.0" cachetools matplotlib
conda activate vega
pip install mcfit
```

**Comment by andreicuceu** [comment]
Addressed in 03a0f67. Thank you!
