### ISSUE TITLE
build_config.py crashes when file is not in a git clone 

### ISSUE THREAD

**Issue by julienguy** [andreicuceu/lyafit#120]
build_config.py crashes at the line 
```
git_hash = git.Repo(vega_path.parents[0]).head.object.hexsha
```
when the code is not from a git clone. This is the case when a tar file is downloaded instead from the list of tags. For instance
```
wget https://github.com/andreicuceu/vega/archive/refs/tags/v0.4.2.tar.gz
```

**Comment by andreicuceu** [comment]
This was solved in [v0.4.3](https://github.com/andreicuceu/vega/releases/tag/v0.4.3). However, when using the tar file, vega is not a valid git repository, so we cannot save the git hash. Therefore, the recommended way to install vega is through `git clone`.
