### ISSUE TITLE
sampler installation instructions

### ISSUE THREAD

**Issue by iprafols** [andreicuceu/lyafit#121]
I was trying to use the sampler with Andrea and found that the installation instructions are incomplete. If you just follow the instructions, then the libraries are not properly linked. You need to add the path to the libraries. 

In my case I do `export LD_LIBRARY_PATH=/global/homes/i/iprafols/desi/git/PolyChordLite/lib:${LD_LIBRARY_PATH}`

This needs to be run in every terminal but can be added to the `.bashrc` (or `.basrhc.ext`) file for automatic running of the export.

It'd be good to add these few extra lines to the installation instructions

**Comment by andreicuceu** [comment]
Thanks @iprafols. The readme has been updated to include this in #123.
